"""Add core models

Revision ID: 854f01fe5992
Revises: 44c0b4fda648
Create Date: 2025-05-03 09:56:28.275564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854f01fe5992'
down_revision = '44c0b4fda648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_product_id', sa.Integer(), nullable=False),
    sa.Column('flavor', sa.String(length=100), nullable=True),
    sa.Column('unit_size_oz', sa.Float(), nullable=False),
    sa.Column('units_per_pack', sa.Integer(), nullable=False),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('threshold_price_per_unit', sa.Float(), nullable=False),
    sa.Column('target_price_per_unit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.Column('vendor_item_id', sa.String(length=100), nullable=True),
    sa.Column('vendor_url', sa.String(length=500), nullable=True),
    sa.Column('package_price', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('price_per_oz', sa.Float(), nullable=False),
    sa.Column('price_vs_threshold', sa.Float(), nullable=False),
    sa.Column('price_vs_target', sa.Float(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('scrape_job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('vendor_price_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.Column('threshold_price', sa.Float(), nullable=False),
    sa.Column('alert_price', sa.Float(), nullable=False),
    sa.Column('alert_channel', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['vendor_price_id'], ['vendor_prices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canonical_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canonical_products', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('category')

    op.drop_table('alerts')
    op.drop_table('vendor_prices')
    op.drop_table('scrape_jobs')
    op.drop_table('product_variants')
    # ### end Alembic commands ###
